// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nujynbcbqlwkmpxpxkeu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im51anluYmNicWx3a21weHB4a2V1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkzMDAzMDcsImV4cCI6MjA1NDg3NjMwN30.C1obqYvcDeCwoSqhlpEap0NtzKIi1_ZCyHCXKZi-qXU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);